language: node_js
node_js:
  - node
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
after_success:
  branches:
    only:
      - master
  - echo "Deploying..."
  - npm install firebase-tools -g
  - firebase deploy --token $FIREBASE_TOKEN
